<block>,<PERIOD>
<block>,<SEMICOLON>
<block>,<BEGIN>
<var_decl_atom>,<BEGIN>
<var_decl_atom>,<PROCEDURE>
<id_comma_atom>,<COLON>
<procedure_declaration_part>,<BEGIN>
<procedure_declaration_part>,<SEMICOLON>
<statement>,<END>
<semicolon_statement_atom>,<END>
<simple_expression_atom>,<SEMICOLON>
<simple_expression>,<EQUAL>
<simple_expression>,<NOT_EQUAL>
<simple_expression>,<LESS>
<simple_expression>,<LESSEQUAL>
<simple_expression>,<GREATEQUAL>
<simple_expression>,<GREATER>
<simple_expression>,<SEMICOLON>
<simple_expression>,<NUMBER>
<simple_expression>,<LPAREN>
<adding_operator_atom>,<EQUAL>
<adding_operator_atom>,<NOT_EQUAL>
<adding_operator_atom>,<LESS>
<adding_operator_atom>,<LESSEQUAL>
<adding_operator_atom>,<GREATEQUAL>
<adding_operator_atom>,<GREATER>
<adding_operator_atom>,<SEMICOLON>
<adding_operator_atom>,<DIV_OP>
<adding_operator_atom>,<RPAREN>
<mult_operator_atom>,<ADD_OP>
<mult_operator_atom>,<SUBTRACT_OP>
<mult_operator_atom>,<OR>
<mult_operator_atom>,<SEMICOLON>
<mult_operator_atom>,<RPAREN>
<sign>,<LPAREN>
<sign>,<NOT_OP>
<sign>,<ID>
<sign>,<NUMBER>
<sign>,<LITCHAR>
<semicolon_statement_atom>,<WRITE>
<write_statement_atom>,<END>
<write_statement_atom>,<WRITE>
<write_statement_atom>,<READ>
<write_statement_atom>,<VAR>
<write_statement_atom>,<RPAREN>
<multiplying_operator>,<NUMBER>
<mult_operator_atom>,<END>
<adding_operator_atom>,<END>
<simple_expression_atom>,<END>
<write_statement_atom>,<SEMICOLON>
<adding_operator_atom>,<EQUAL>
<adding_operator_atom>,<DO>
<adding_operator_atom>,<THEN>